apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-app
  template:
    metadata:
      labels:
        app: bank-app
    spec:
      volumes:
       - name: bankapp-config
         configMap:
           name: bank-app-config
      containers:
        - name: bankapp
          image: saksham1997/bankapp:dev
          ports:
            - containerPort: 8080
          resources: 
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "700m"
              memory: "700Mi"
          volumeMounts:
            - name: bankapp-config
              mountPath: /app/config/application.properties
              subPath: application.properties
          env:
            - name: SPRING_CONFIG_LOCATION
              value: "file:/app/config/application.properties"
